export const projectData = [
  {
    id: 1,
    name: "Personal Portfolio",
    description:
      "A personal portfolio website is a professional website that provides information about what you do, what services you may offer, and how to contact you or your company. Portfolio websites are an easy way to promote yourself, your brand, or your business. It was built with React, Redux, CSS. react-router-dom is used for page navigation and lazy loading elements for website performance",
    path: "assets/project1.png",
    link: "https://premnarayankar-cryptomonster.netlify.app/",
    skills: [
      "React",
      "JavaScript",
      "Responsive Design",
      "react-router-dom",
      "VScode",
      "ES6",
      "CSS",
      "HTML",
    ],
  },
  {
    id: 2,
    name: "Crypto Monster",
    description:
      "Crypto Monster platform is for people who love to know cryptocurrencies listed on the internet. This platform listed more than 100 cryptocurrencies and also you can see the cryptocurrencies' performance through their chart.  It was built with React, Redux-Toolkit, MUI and CSS. It uses CoinGecko API to get cryptocurrency and react-chartjs-2 for charts.react-router-dom is used for page navigation and also uses lazy component loading for better website performance.",
    path: "assets/project2.png",
    link: "https://premnarayankar-cryptomonster.netlify.app/",
    skills: [
      "React",
      "Redux-Toolkit",
      "react-router-dom",
      "Material UI",
      "CoinGeko API",
      "JavaScript",
      "Responsive Design",
      "VScode",
      "ES6",
      "CSS",
      "HTML",
    ],
  },
  {
    id: 3,
    name: "Shopping Cart",
    description:
      "This project is a smaller version of an e-commerce website. On this website, you can mimic like you are buying products. you can sort and search the products from the list. In the end, you will really like the experience. It was built with React, Redux, React-Bootstrap and CSS. All products in this project were created using Faker. JS and Redux-Toolkit are used for state management and lazy loading for better website performance.",
    path: "assets/project3.png",
    link: "https://premnarayankar-shopping-cart.netlify.app/",
    skills: [
      "React",
      "Redux",
      "react-router-dom",
      "Faker.JS",
      "React-Bootstrap",
      "Bootstrap",
      "JavaScript",
      "Responsive Design",
      "VScode",
      "ES6",
      "CSS",
      "HTML",
    ],
  },
  {
    id: 4,
    name: "Contact Manager",
    description:
      "Contact Manager project is an application specially built to keep track of contact details. This application will be like a contact storage keeper where the user would be able to create a new contact, edit stored contact, and delete the contact. You can search for contact through their name, email, and number. It was built with React, Redux, React-Bootstrap and CSS. It uses LocalStorage to store data locally.",
    path: "assets/project4.png",
    link: "https://premnarayankar-contact-manager.netlify.app/",
    skills: [
      "React",
      "Redux",
      "Bootstrap",
      "JavaScript",
      "Responsive Design",
      "LocalStorage",
      "VScode",
      "ES6",
      "CSS",
      "HTML",
    ],
  },
  {
    id: 5,
    name: "Elephant Theme",
    description:
      "Elephant Theme project is a single-page elephant theme website built using pure HTML, CSS, and JavaScript, the website is fully responsive.",
    path: "assets/project5.png",
    link: "https://premnarayankar-elephant-website.netlify.app/",
    skills: ["JavaScript", "Responsive Design", "ES6", "CSS", "HTML"],
  },
];
